language: julia
os:
  - linux
  - osx

julia:
  - 1.1
  - nightly

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  exclude:
    - os: windows
      julia: nightly
      language: julia

  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia

  allow_failures:
  - julia: nightly
  - os: osx
  - os: windows

addons:
  apt_packages:
    - gfortran

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia --project --color=yes -e "import Pkg; Pkg.build(); Pkg.instantiate()"
  - julia --check-bounds=yes --depwarn=no --inline=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("PowerSimulations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project -e 'using Pkg; Pkg.build(); Pkg.add("Documenter"); Pkg.instantiate()'
        - julia --project=docs/ -e 'ENV["DOCUMENTER_DEBUG"] = "true"; include("docs/make.jl")'
      after_success: skip
