name = "PowerSimulations"
uuid = "e690365d-45e2-57bb-ac84-44ba829e73c4"
authors = ["Jose Daniel Lara", "Dheepak Krishnamurthy", "Clayton Barrows"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
AxisArrays = ">= v0.3.0"
DataFrames = ">= v0.18.1"
JuMP = ">= v0.19.1"
MathOptInterface = ">= v0.8.4"
ParameterJuMP = ">= v0.1.0"
PowerModels = ">= v0.10.0"
PowerSystems = ">= v0.3.2"
TimeSeries = ">= v0.14.1"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OSQP", "Memento", "Ipopt", "GLPK"]
